language: python
python:
  - "2.6"
  - "2.7"
before_install:
  # As numpy is needed for running setup.py, it must be installed
  # *before* running tox
  pip --quiet install numpy
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then tox -e py26 /tmp; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27 /tmp; fi
