language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=doc
before_install:
  - pip install --quiet --use-mirrors tox
  # Install GSL (and log it's version number)
  - apt-cache show libgsl0-dev | grep -i version
  - sudo apt-get install -qq libgsl0-dev
script:
  - tox
